spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration: 1800000
    refresh-token-expiration: 2592000000
  frontend:
    url: ${FRONTEND_URL}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}